package subtitles.player;

import java.io.*;
import java.util.concurrent.Executors;
import javax.swing.*;
import subtitleFile.*;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.Callable;
import java.util.concurrent.Future;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author miroshko
 */
public class ApplicationForm extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationForm
     */
    public ApplicationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subtitleFileChooser = new javax.swing.JFileChooser();
        openSubtitleFile = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        progressSlider = new javax.swing.JSlider();
        timePositionLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        openSubtitleFile.setText("Open");
        openSubtitleFile.setToolTipText("");
        openSubtitleFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSubtitleFileActionPerformed(evt);
            }
        });

        status.setText("No file is open");
        status.setToolTipText("");

        playButton.setText("▶");
        playButton.setToolTipText("");
        playButton.setEnabled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("▐▐");
        pauseButton.setToolTipText("");
        pauseButton.setEnabled(false);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        progressSlider.setMaximum(200);
        progressSlider.setValue(0);
        progressSlider.setEnabled(false);
        progressSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                progressSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                progressSliderMouseReleased(evt);
            }
        });
        progressSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progressSliderStateChanged(evt);
            }
        });
        progressSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                progressSliderMouseDragged(evt);
            }
        });

        timePositionLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        timePositionLabel.setText("0:00");
        timePositionLabel.setEnabled(false);

        subtitleLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openSubtitleFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timePositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(subtitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openSubtitleFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(timePositionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openSubtitleFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSubtitleFileActionPerformed
        int returnVal = subtitleFileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            currentFile = subtitleFileChooser.getSelectedFile();
            OpenCurrentFile();
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_openSubtitleFileActionPerformed

    private File currentFile;
    private TimedTextObject timedText;
    private int currentPosition = 0;
    private int resolution = 10; // ms
    private ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    private Future schedulerFuture;
    
    private String formatTime(int milliseconds) {
        int seconds = (int) (milliseconds / 1000) % 60;
        int minutes = (int) ((milliseconds / (1000*60)) % 60);
        int hours   = (int) ((milliseconds / (1000*60*60)) % 24);
        String formatted = String.format("%02d:%02d", minutes, seconds);
        if (hours > 0) {
            formatted = String.format("%d:", hours) + formatted;
        }
        return formatted;
    }
    
    private String getTextOnCurrentPosition() {
        int prevKey = timedText.captions.firstKey();
        for(int key: timedText.captions.keySet()) {
            if(key > currentPosition) {
              break;  
            }
            prevKey = key;
        }
        Caption currCaption = timedText.captions.get(prevKey);
        if (currCaption.start.getMseconds() < currentPosition &&
            currCaption.end.getMseconds() > currentPosition) {
                return currCaption.content;
        }
        return "";
    }

    private void play() {
        schedulerFuture = scheduler.scheduleAtFixedRate(new Runnable() {
            public void run() {
                currentPosition += resolution;
                reflectPosition();
            }        
        }, 0, resolution, TimeUnit.MILLISECONDS);

        pauseButton.setEnabled(true);
        playButton.setEnabled(false);
    }
    
    private void reflectPosition() {
        progressSlider.setValue(currentPosition);
        timePositionLabel.setText(formatTime(currentPosition));
        subtitleLabel.setText(getTextOnCurrentPosition());
    }
    
    private void pause() {
        schedulerFuture.cancel(true);
        pauseButton.setEnabled(false);
        playButton.setEnabled(true);
    }
    
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        play();
    }//GEN-LAST:event_playButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        pause();
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void progressSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progressSliderStateChanged
        currentPosition = progressSlider.getValue();
        reflectPosition();
    }//GEN-LAST:event_progressSliderStateChanged

    private void progressSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressSliderMouseDragged

    }//GEN-LAST:event_progressSliderMouseDragged

    boolean pausedOnMousePressed;
    private void progressSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressSliderMousePressed
        pausedOnMousePressed = schedulerFuture == null || schedulerFuture.isCancelled();
        if (!pausedOnMousePressed)
            pause();
    }//GEN-LAST:event_progressSliderMousePressed

    private void progressSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressSliderMouseReleased
        if (!pausedOnMousePressed)
            play();
    }//GEN-LAST:event_progressSliderMouseReleased

    
    private void enableControls() {
        playButton.setEnabled(true);
        pauseButton.setEnabled(false);
        progressSlider.setEnabled(true);
    }
    
    private void disableControls() {
        
    }
   

    private void OpenCurrentFile() {
        status.setText(String.format("Opened file: %s", currentFile.getName()));
        FormatSRT srt = new FormatSRT();
        try {
            InputStream is = new FileInputStream(currentFile);
            timedText = srt.parseFile(currentFile.getAbsolutePath(), is);
            int length = timedText.captions.lastEntry().getValue().end.getMseconds();
            progressSlider.setMaximum(length);
            status.setText("File read successfully");
            enableControls();
        } catch (IOException e) {
            status.setText("Error opening file");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton openSubtitleFile;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton playButton;
    private javax.swing.JSlider progressSlider;
    private javax.swing.JLabel status;
    private javax.swing.JFileChooser subtitleFileChooser;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel timePositionLabel;
    // End of variables declaration//GEN-END:variables
}
